In [ ]:
#variable
a=10
print("I am 10 years old")


I am 10 years old


In [ ]:
#String and variables
a=10
print("I am",a,"years old")

I am 10 years old


In [ ]:
#Adding of two integer variables
a=int(input("Enter a value: "))
b=int(input("Enter b value: "))
print("the sum is",a+b)


Enter a value: 703
Enter b value: 900
the sum is 1603


In [ ]:
#Arithmetic Operations on two integer variables
a=int(input("Enter a value: "))
b=int(input("Enter b value: "))
print("Sum is",a+b)
print("Difference is",a-b)
print("Product is",a*b)
print("Quotient is",a/b)
print("Remainder is",a%b)
print("Power of a to b is",a**b)
print("Floor Division is",a//b)

Enter a value: 25
Enter b value: 90
Sum is 115
Difference is -65
Product is 2250
Quotient is 0.2777777777777778
Remainder is 25
Power of a to b is 652530446799852452671029410925654755570116425806896654775863645546972324459748622722289612685386828161426819860935211181640625
Floor Division is 0


In [ ]:
#Take salary from the user,if the salary is more than 50000 there is a 10% tax,Print his final salary?
a=int(input("Enter salary: "))
if ( a>50000):
  tax = (10/100)*a
  a=a-tax
  print("After tax deduction,your salary is: ",a)
else:
    print("No tax deduction,your salary is: ",a)




Enter salary: 90000
After tax deduction,your salary is:  81000.0


In [ ]:
#Get the  salary from the user if the salary is more than or equal to 50000 apply 10% tax deduction if the salary is less then 50000 apply 5% tax if the salary is more than 70000 then apply 12% tax if the salary exceeds 1lakh print your are promoted to next level
salary = int(input("Enter your salary: "))
if salary >= 100000:
    print("Congratulations! You are promoted to the next level.")
    tax_percentage = 10
elif salary >= 70000:
    tax_percentage = 12
elif salary >= 50000:
    tax_percentage = 10
else:
    tax_percentage = 5
tax_amount = (tax_percentage / 100) * salary
net_salary = salary - tax_amount
print("Your salary before tax: {salary}")
print("Tax deduction at {tax_percentage}%: {tax_amount}")
print("Your net salary after tax: {net_salary}")


Enter your salary: 100000
Congratulations! You are promoted to the next level.
Your salary before tax: {salary}
Tax deduction at {tax_percentage}%: {tax_amount}
Your net salary after tax: {net_salary}


In [ ]:
#For loop
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#for loop 1
n=int(input("Enter n value: "))
for i in range(1,20):
  print(n,"X",i,"=",n*i)


Enter n value: 19
19 X 1 = 19
19 X 2 = 38
19 X 3 = 57
19 X 4 = 76
19 X 5 = 95
19 X 6 = 114
19 X 7 = 133
19 X 8 = 152
19 X 9 = 171
19 X 10 = 190
19 X 11 = 209
19 X 12 = 228
19 X 13 = 247
19 X 14 = 266
19 X 15 = 285
19 X 16 = 304
19 X 17 = 323
19 X 18 = 342
19 X 19 = 361


In [ ]:
#While loop
n=int(input("Enter n value: "))
i=1
while i < 11:
  b = n * i
  print(n," * ",i," = ",b)
  i = i + 1

Enter n value: 15
15  *  1  =  15
15  *  2  =  30
15  *  3  =  45
15  *  4  =  60
15  *  5  =  75
15  *  6  =  90
15  *  7  =  105
15  *  8  =  120
15  *  9  =  135
15  *  10  =  150


In [ ]:
#list:heterogeneous
l1=[1,'kill',89,'chat',9.1,'True']
print(l1)

[1, 'kill', 89, 'chat', 9.1, 'True']


In [ ]:
#mutable:
l1.append("appended")
print(l1)

[1, 'kill', 89, 'chat', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended']
[1, 'kill', 89, 'chat', 'inserted', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended']


In [ ]:
#insert
l1.insert(4,"inserted")
print(l1)

[1, 'kill', 'chat', 'inserted', 'inserted', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended', 'ammu', 'berry', 'ammu', 'berry']


In [ ]:
#extend
l2= ["ammu","berry"]
#list1.extend(list2)
l1.extend(l2) #l1 = l1+l2
print(l1)

[1, 'kill', 89, 'chat', 'inserted', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended', 'ammu', 'berry', 'ammu', 'berry']
[1, 'kill', 'chat', 'inserted', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended', 'ammu', 'berry', 'ammu', 'berry']


In [ ]:
#pop
l1.pop(2)
print(l1)

[1, 'kill', 'inserted', 'inserted', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended', 'ammu', 'berry', 'ammu', 'berry']


In [ ]:
#remove
l1.remove("kill") #listname.remove(element)
print(l1)

[1, 'inserted', 'inserted', 'inserted', 9.1, 'True', 'append', 'append', 'ammu', 'berry', 'appended', 'ammu', 'berry', 'ammu', 'berry']


In [ ]:
#clear
l1.clear()
print(l1)

[]


In [ ]:
#create a list of 10 integer elements and print their squares save these squares in a new list
l1=[25,29,45,90,120,150,167,205,209,215]
res = []
for i in l1:
  res.append(i*i)
print(res)




[625, 841, 2025, 8100, 14400, 22500, 27889, 42025, 43681, 46225]


In [ ]:
l1=[24,25,30,45,67]
res = [i*i for i in l1]
print(res)

[576, 625, 900, 2025, 4489]


In [ ]:
#LC
#newlist = [(st of if) if (cond) else (st of else)]
l1 = [23,67,12,34,69]
res =[i*i if i>50 else 'X' for i in l1]
print(l1)

In [ ]:
#take the salary from the user if the salary is less then 50k 10per tax otherwise 15per tax
sal_list = [55000,58000,65000,25000,30000]
res = [i-i*0.1 if i<50000 else i-i*0.15 for i in sal_list]
print(res)

[46750.0, 49300.0, 55250.0, 22500.0, 27000.0]


In [ ]:
#dictionary
dict1 = {"mentor":'jwalitha',"student":'pallavi',44:'ammu',45:'varshi',46:'prani'}
print(dict1)

{'mentor': 'jwalitha', 'student': 'pallavi', 44: 'ammu', 45: 'varshi', 46: 'prani'}


In [ ]:
dict1 = {"mentor":'jwalitha',"student":'pallavi',44:'ammu',45:'varshi',46:'prani'}
print(dict1.keys())

dict_keys(['mentor', 'student', 44, 45, 46])


In [ ]:
dict1 = {"mentor":'jwalitha',"student":'pallavi',44:'ammu',45:'varshi',46:'prani'}
print(dict1.values())

dict_values(['jwalitha', 'pallavi', 'ammu', 'varshi', 'prani'])


In [ ]:
d1 = {"Dept":"cse","details": {"year":"II","sec":"D","count":71}}
print(d1)

{'Dept': 'cse', 'details': {'year': 'II', 'sec': 'D', 'count': 71}}


In [ ]:
d1 = {"Dept":"cse","details": {"year":"II","sec":"D","count":71}}
print(dict1[45])

varshi


In [ ]:
d1 = {"Dept":"cse","details": {"year":"II","sec":"D","count":71}}
print("year is",d1["details"]["year"])
print("section is",d1["details"]["sec"])
print("strength is",d1["details"]["count"])

year is II
section is D
strength is 71


In [ ]:
id1 = [34,56,78,39,100]
names = ["joe","suji","prabhas","shankar","anu"]
new_zip = (zip(id1,names))
for i in new_zip:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'prabhas')
(39, 'shankar')
(100, 'anu')


In [ ]:
id1 = [34,56,78,39,100]
names = ["joe","suji","prabhas","shankar","anu"]
new_dict = dict(zip(id1,names))
print(new_dict)

{34: 'joe', 56: 'suji', 78: 'prabhas', 39: 'shankar', 100: 'anu'}


In [ ]:
#numpy
import numpy as np
A = np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)



1
(4,)


In [ ]:
#creating 2d array
A = np.array([[1,2],[3,4],[5,6]])
print(A.ndim)
print(A.shape)

2
(3, 2)


In [ ]:
A = np.array([[1,2,3,4],[3,4,5,6]])
#elements in each roe = columns
print(A.ndim)
print(A.shape)
print(A)

2
(2, 4)
[[1 2 3 4]
 [3 4 5 6]]


In [ ]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A.ndim)
print(A.shape)
print(A)


3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
A = np.ones((4,3))#g,r,c
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A = np.zeros((4,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
A = np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A = np.arange(1,15,2) #START,STOP,STEP
print(A)
print(type(A))

[ 1  3  5  7  9 11 13]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using arange function between 1 & 1000
A = np.arange(8,1001,8)
print(A)


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
A = np.linspace(45,60,12) #Splitting a range  of numbers into n numbers with common difference
print(A)

[45.         46.36363636 47.72727273 49.09090909 50.45454545 51.81818182
 53.18181818 54.54545455 55.90909091 57.27272727 58.63636364 60.        ]


In [ ]:
#read tuple and sets
#documentation
#qr codes

In [1]:
a = [8,6,7,12,3,18]
a.sort()
print(a)

[3, 6, 7, 8, 12, 18]


In [2]:
a = [8,6,7,12,3,18]
b = sorted(a)
print(b)

[3, 6, 7, 8, 12, 18]


In [3]:
a = (12,35,17,10,50)
b = sorted(a)
print(a)
print(b)

(12, 35, 17, 10, 50)
[10, 12, 17, 35, 50]
